twig:
    file_name_pattern: '*.twig'
    form_themes: ['form/pollaris_theme.html.twig']
    globals:
        appName: '%app.name%'
        emailsEnabled: '%app.emails_enabled%'

when@test:
    twig:
        strict_variables: true
